# Generated by Django 3.0.6 on 2020-05-23 09:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsActiveImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('active_name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('active_images', models.ImageField(upload_to='goods', verbose_name='活动图片')),
                ('active_link', models.CharField(max_length=128, verbose_name='活动链接')),
            ],
            options={
                'verbose_name': '商品活动图片',
                'verbose_name_plural': '商品活动图片',
                'db_table': 'df_goods_active_images',
            },
        ),
        migrations.CreateModel(
            name='GoodsIndexImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('images', models.ImageField(upload_to='goods', verbose_name='轮播图片')),
                ('index', models.IntegerField(verbose_name='图片序号')),
            ],
            options={
                'verbose_name': '轮播图片表',
                'verbose_name_plural': '轮播图片表',
                'db_table': 'df_goods_index_images',
            },
        ),
        migrations.CreateModel(
            name='GoodsKinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=20, verbose_name='商品种类')),
                ('logo', models.CharField(max_length=10, verbose_name='商品logo')),
                ('images', models.ImageField(upload_to='goods', verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '商品种类表',
                'verbose_name_plural': '商品种类表',
                'db_table': 'df_goods_kinds',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=50, verbose_name='商品SPU名称')),
                ('details', tinymce.models.HTMLField(blank=True, verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'df_goods_spu',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goods_name', models.CharField(max_length=20, verbose_name='商品名称')),
                ('brief', models.CharField(max_length=50, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('unit', models.CharField(max_length=10, verbose_name='单位')),
                ('stock', models.FloatField(verbose_name='库存')),
                ('sales_volume', models.IntegerField(default=0, verbose_name='销量')),
                ('pictures', models.CharField(max_length=50, verbose_name='图片')),
                ('status', models.SmallIntegerField(choices=[('1', '上架'), ('0', '下架')], default=1, verbose_name='商品状态')),
                ('SPU_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU')),
                ('kinds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsKinds', verbose_name='商品种类')),
            ],
            options={
                'verbose_name': '商品配置表',
                'verbose_name_plural': '商品配置表',
                'db_table': 'df_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('images', models.ImageField(upload_to='goods', verbose_name='商品图片')),
                ('goods_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU', verbose_name='商品名称')),
            ],
            options={
                'verbose_name': '商品图片表',
                'verbose_name_plural': '商品图片表',
                'db_table': 'df_goods_images',
            },
        ),
    ]
