# Generated by Django 3.0.7 on 2020-06-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200526_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssku',
            name='SPU_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSPU'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='pictures',
            field=models.ImageField(upload_to='goods', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '上架'), (0, '下架')], default=1, verbose_name='商品状态'),
        ),
    ]
