# Generated by Django 3.0.6 on 2020-05-23 09:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goods_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('comment', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'df_order_goods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDel', models.BooleanField(default=False, verbose_name='删除标记')),
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('pay_ways', models.SmallIntegerField(choices=[('1', '支付宝'), ('2', '微信'), ('3', '银行卡')], verbose_name='支付方式')),
                ('amount', models.IntegerField(verbose_name='总数量')),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费')),
                ('pay_status', models.SmallIntegerField(choices=[('1', '支付成功'), ('2', '待支付'), ('3', '已取消')], verbose_name='支付状态')),
            ],
            options={
                'verbose_name': '订单信息表',
                'verbose_name_plural': '订单信息表',
                'db_table': 'df_order_info',
            },
        ),
    ]
