# Generated by Django 3.0.6 on 2020-05-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200523_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
