# Generated by Django 3.0.6 on 2020-05-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200523_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='SKU_id',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='ordergoods',
            old_name='order_id',
            new_name='order',
        ),
    ]
