# Generated by Django 3.0.7 on 2020-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200523_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.SmallIntegerField(choices=[('1', '支付成功'), ('0', '待支付'), ('2', '已取消')], verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_ways',
            field=models.SmallIntegerField(choices=[('0', '货到付款'), ('1', '支付宝'), ('2', '微信'), ('3', '银行卡')], verbose_name='支付方式'),
        ),
    ]
