# Generated by Django 3.0.7 on 2020-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200611_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
    ]
